# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
